### ISSUE TITLE
Progress indication

### ISSUE THREAD

**Issue by maedoc** [brian-lau/MatlabStan#10]
It would be nice to have some indication of progress. I currently keep `fit.process(1, 1).stdout` open in the variable explorer, but an ETA on the StanFit object could be nice, so e.g. I can refill my coffee if it's going to be a while.

I can try this and send a PR if you like (since I'm anyhow waiting for the sampling...)

**Comment by maedoc** [comment]
Sorry I missed the `check` method, so maybe this is superfluous.

**Comment by brian-lau** [comment]
Updated the wiki: 
https://github.com/brian-lau/MatlabStan/wiki/Printing-progress-information-to-screen
