### ISSUE TITLE
Allow data to have numeric arrays with more than 2 dimensions

### ISSUE THREAD

**Issue by avehtari** [brian-lau/MatlabStan#11]
Currently rdump.m ignores numeric arrays with more than 2 dimensions
https://groups.google.com/forum/#!topic/stan-users/Vs1Cs12SKUQ

Should add additional isnumeric check and
 1) write to file numeric arrays with more than 2 dimensions
 2) give error if the data is not numeric

**Comment by brian-lau** [comment]
Fixed in commit a9d1f19
