### ISSUE TITLE
"extract" fails when dimensionality of a param is greater than number of samples drawn

### ISSUE THREAD

**Issue by kevin-j-miller** [brian-lau/MatlabStan#12]
Hi Brian,

I've been playing around with MatlabStan for a few weeks now, and it's a wonderful tool! Thanks for building it!  I ran into an issue this afternoon where the "extract" function was failing, giving error:

    Index exceeds matrix dimensions. 
    Error in mcmc/extract (line 175)
                   temp = temp(self.permute_index(1:max(sz)),:);

This was happening specifically when max(sz) was not equal to the number of samples drawn, due to a transformed parameter in my model with very large dimensionality. I was able to fix the problem in my case by replacing "max(sz)" with "sz(1)" in the offending line of code.

Thanks!

Kevin

**Comment by brian-lau** [comment]
Hi Kevin,

This bug came up in another context, and I believe your problem will also be fixed fixed by 00711bfa
