### ISSUE TITLE
Variational inference

### ISSUE THREAD

**Issue by genenk** [brian-lau/MatlabStan#19]
CmdStan recently added variational inference method. Can this be accessed from MatlabStan currently?

**Comment by brian-lau** [comment]
This should be possible. I'll work on exposing this feature.

**Comment by genenk** [comment]
Brilliant, thank you. Btw, someone else also asked about this on the stan-users group.

https://groups.google.com/forum/#!topic/stan-users/t-i8gUT4lkQ

**Comment by genenk** [comment]
Hi Brian, any luck with that? I see the Julia interface has this feature. Maybe their implementation can help somehow?

Thanks.

**Comment by brian-lau** [comment]
Completed in commit b2189ae8
