### ISSUE TITLE
Large double values in data can cause an error

### ISSUE THREAD

**Issue by avehtari** [brian-lau/MatlabStan#2]
If data has large double values which should be represented using scientific notation, rdump.m may write them as integers which are larger than maxint('int32'), causing Stan to give an error, e.g.,

| Exception: data y value 10683812715190712 beyond int range

The problem is in the rdump.m 
fprintf(fid,'%d, ',data{i}(1:end-1))
where %d is used for reals, too. If the floating point representation of a large value happens to be an integer and in 64bit Matlab smaller than max('int64') then Matlab prints the value as an integer. Stan uses int32 and gives an error if an integer is larger than intmax('int32').

**Comment by brian-lau** [comment]
Merged into master dadbb7e
