### ISSUE TITLE
Problem with Getting started example

### ISSUE THREAD

**Issue by silfves1** [brian-lau/MatlabStan#21]
I downloaded from the Stan website all the packages mentioned in Matlabstan - Getting Started according to the instructions. However, my Matlab2015b gives me this error message gives me this error message when I try to run the given script by copy-pasteing it or when downloading the eight_schools.stan -file and running the code line below it:

Error using StanModel/set.stan_home (line 311)
Does not look like a proper stan setup

Error in StanModel (line 184)
         self.stan_home = p.Results.stan_home;

Error in stan (line 108)
   model = StanModel();

I checked with path-command that all the necessary folders (below MatlabStan-2.7.0.0 and MatlabProcessManager folder's two .m-files) are in the path. In the Matlab workspace I have those same folders and files. I have put the path to MatlabStan-2.7.0.0 in stan_home.m with this exact line:

d = '/Users/sebastiansilfverberg/Documents/MATLAB/BDA/MatlabStan-2.7.0.0/cmdstan-2.9.0';

+mstan -folder is directly below MatlabStan-2.7.0.0.

Can you tell me what seems to be the problem? I'm using Max with OSX 10.11.2

**Comment by claysope** [comment]
I'm actually having the same problem. I was able to get everything to work on my Mac (OS X 10.11.3) running Matlab 2014b and Matlab 2015b. However, now that I am trying to get everything to run on my Windows machine, I get the following error:

Error using StanModel/set.stan_home (line 311)
Does not look like a proper stan setup

Error in StanModel (line 184)
         self.stan_home = p.Results.stan_home;


Similarly, I'm running the latest versions of MatlabStan, cmdstan, and MatlabProcessManager. I've tried Matlab 2014a and Matlab 2015b on my Windows machine (Windows 7 Professional v6.1). I also put the correct path in stan_home.m. 

I feel like I must have installed something incorrectly, so I reinstalled everything. I get the same problem. I've been racking my brain for the last few hours, but I haven't found a solution. 

silfves1, did you figure your problem out?

**Comment by claysope** [comment]
I've been trying to figure this out all morning and have remained unsuccessful. I can get everything to run without any problems in R on this Windows machine, but Matlab still spits out the same error message "Does not look like a proper stan setup". It seems to not be creating a 'cmdstan-2.9.0\bin' directory that is needed to run cmdstan.

Has anyone else encountered this problem?

**Comment by silfves1** [comment]
Brian answered me that the main problem was that I haven’t had compiled cmdstan in the terminal before hand. After that all problems disappeared. Please see the cmdstan manual and examples in the Stan website to see, how the compiling is done. Then it should be fine.

--
Sebastian Silfverberg


Päällä 25. helmikuuta 2016 klo 1.17.04, Peter Clayson (notifications@github.com<mailto:notifications@github.com>) kirjoitti:

I'm actually having the same problem. I was able to get everything to work on my Mac (OS X 10.11.3) running Matlab 2014b and Matlab 2015b. However, now that I am trying to get everything to run on my Windows machine, I get the following error:

Error using StanModel/set.stan_home (line 311)
Does not look like a proper stan setup

Error in StanModel (line 184)
self.stan_home = p.Results.stan_home;

Similarly, I'm running the latest versions of MatlabStan, cmdstan, and MatlabProcessManager. I've tried Matlab 2014a and Matlab 2015b on my Windows machine (Windows 7 Professional v6.1). I also put the correct path in stan_home.m.

I feel like I must have installed something incorrectly, so I reinstalled everything. I get the same problem. I've been racking my brain for the last few hours, but I haven't found a solution.

silfves1, did you figure your problem out?

**Comment by claysope** [comment]
Thanks, silfves1. Ya, I went to the Windows-specific instructions then didn't go back to continue the rest of the installation guide. Thank you for the feedback. Everything works now.

**Comment by silfves1** [comment]
I’m glad to hear that!

--
Sebastian Silfverberg


Päällä 27. helmikuuta 2016 klo 19.22.38, Peter Clayson (notifications@github.com<mailto:notifications@github.com>) kirjoitti:

Thanks, silfves1. Ya, I went to the Windows-specific instructions then didn't go back to continue the rest of the installation guide. Thank you for the feedback. Everything works now.
