### ISSUE TITLE
When the address to the working directory has spaces

### ISSUE THREAD

**Issue by Marina-Antillon** [brian-lau/MatlabStan#22]
Hi all,

I am new to stan and I am using it in a Mac with MATLAB R2014b. I have gotten Matlab to work from the folder 'User/Marina/Documents/Stan_matlab' but I cannot get Stan to work from a working directory that has spaces it its address:

Error using StanModel/compile (line 852)
make: **\* No rule to make target `/Users/Marina/Google'.  Stop.

The issue is that I keep all of my schoolwork in Google Drive, which is provided by my school (and which has an address with a space in it). There are a number of spaces in some of my directories (suboptimal, I know, but I also share these with some people) and I wanted to see if there was a way to change the matlab interface to stan so that stan may run from any directory in my computer.

If this is not possible, I can run stan from some other directory, but I would prefer to have all items regarding a project in one place (which sometimes means having them in folders that have spaces in their name.

Thanks,
Marina

**Comment by brian-lau** [comment]
Stan binaries are built using make, which does not appear to handle spaces easily. 
https://www.cmcrossroads.com/article/gnu-make-meets-file-names-spaces-them
http://stackoverflow.com/questions/9838384/can-gnu-make-handle-filenames-with-spaces
http://savannah.gnu.org/bugs/?712

This seems complex enough that I'm gonna recommend not using spaces for now.

**Comment by Marina-Antillon** [comment]
Yeah, I had to change to a directory with an address with no spaces. A bit
of a workaround, but it was easier than learning how to fix it. Thanks!
