### ISSUE TITLE
Undefined variable in mcmc.m

### ISSUE THREAD

**Issue by DanielNScott** [brian-lau/MatlabStan#23]
When I call stan as...

```matlab
RL_data = struct('n_s',ns,'n_t',nt,'Choice',choices,'Correct',outcomes,...
                 'Reward',rewards,'Subject',subj_nums,'Init',inits);

fitRL = stan('file','opzet_stan_kort_anne_2.stan','data',RL_data,'iter',1000,...
             'chains',4,'refresh',100,'warmup',500,'thin',10);
```

I get the following error:

```matlab
??? Undefined function or variable 'rng'.

Error in ==> mcmc>mcmc.mcmc at 37
            self.rng_state = rng;

Error in ==> StanFit>StanFit.StanFit at 94
            self.sim_ = mcmc();

Error in ==> StanModel>StanModel.sampling at 744
         fit = StanFit('model',copy(self),'processes',p,...

Error in ==> stan at 137
   fit = model.sampling(p.Unmatched);

Error in ==> testRL_stan2 at 59
fitRL = stan('file','opzet_stan_kort_anne_2.stan','data',RL_data,'iter',1000,...
```

As far as I can tell right now it is not an issue with my call to STAN, but I may be wrong about this. Does anyone know what may be wrong? I wasn't planning on being a MatlabSTAN contributor, just a user, but I guess I might need to fix this if it isn't just operator-error.

**Comment by DanielNScott** [comment]
Looks like this is actually a backwards compatibility issue, and I need to use a newer version of Matlab.

**Comment by brian-lau** [comment]
I'm not sure when rng() was introduced. I don't have a version without this function, but if you tell me how to set the random number seed in your version, we could build in some backwards compatibility.

**Comment by DanielNScott** [comment]
I looked into it a bit and it seems like updating my version of matlab is the best idea. Thanks though. =)
