### ISSUE TITLE
clarification on .extract() method

### ISSUE THREAD

**Issue by drbenvincent** [brian-lau/MatlabStan#26]
Hi. Thanks for this great piece of software.
Can I request a specific and expanded wiki section on the `extract()` method? At the moment there is just a small bit of info on the Getting Started page and I was left with a few questions.

For example, I can tell that the `fit.extract('permuted',true);` command flattens samples over chains, but I am not 100% sure if it also randomises the ordering of the samples.

**Comment by brian-lau** [comment]
Wiki page added for sample extraction:
https://github.com/brian-lau/MatlabStan/wiki/Extracting-samples

Yes, setting `permuted` true in `extract` randomizes the ordering of samples.
