### ISSUE TITLE
Example with user-defined initial values

### ISSUE THREAD

**Issue by mdnunez** [brian-lau/MatlabStan#31]
How does one define initial values per chain per parameter in MatlabStan? I could not find an example on the wiki. Defining initial values incorrectly causes an "Warning: Stan seems to have exited badly." error.

**Comment by brian-lau** [comment]
There currently isn't a way to set different initial values for each chain. This has been requested before, so I can have a look at adding this feature.

If you are having a problem setting initial values in general (not per chain), can you paste in an example?

**Comment by brian-lau** [comment]
I've updated the wiki to include examples on parameter initializations:

https://github.com/brian-lau/MatlabStan/wiki/Initializing-parameters

**Comment by mdnunez** [comment]
Thank you! This solves the initial problem of not having a wiki example.

**Comment by brian-lau** [comment]
Separate inits for each chain added with commit ef1666a1. Examples at the bottom of the wiki page here: https://github.com/brian-lau/MatlabStan/wiki/Initializing-parameters/_edit#different-inits-can-be-specified-for-each-chain
