### ISSUE TITLE
Running MatlabStan

### ISSUE THREAD

**Issue by skaticha** [brian-lau/MatlabStan#33]
I tried to run the rats example but I get the following error message:

Undefined variable "mstan" or class "mstan.stan_home".

Error in StanModel (line 170)
         p.addParamValue('stan_home',mstan.stan_home);

Error in stan (line 108)
   model = StanModel();

Error in rats (line 20)
fit = stan('file','rats.stan','data',rats_dat,'verbose',true);

Anyone know how to get it to run? I know cmdStan is working as I was able to run the Bernoulli example.
Thanks

**Comment by brian-lau** [comment]
Looks like the matlab package +mstan folder is not in your path.

**Comment by skaticha** [comment]
I've made sure the folder is in the path and modified the stan_home.m to point to my CmdStan installation. The error message changed to the following:

Error using StanModel/set.file (line 332)
File does not exist

Error in StanModel/set (line 275)
               self.file = p.Results.file;

Error in StanModel/sampling (line 730)
         self.set(varargin{:});

Error in stan (line 138)
      fit = model.sampling(p.Unmatched);

Error in rats (line 20)
fit = stan('file','rats.stan','data',rats_dat,'verbose',true);

**Comment by brian-lau** [comment]
Looks like the `rats.stan` file is not in your current directory. You can download it here:

https://raw.githubusercontent.com/brian-lau/MatlabStan/master/Examples/rats.stan

**Comment by skaticha** [comment]
This is not the issue. I already had the file rats.stan in the Examples folder

**Comment by brian-lau** [comment]
Is your current working directory the `Examples` folder? The error you are getting is simply saying the rats.stan file cannot be found (using Matlab's `exist` function). So, either the file is not in your current directory, or `Examples` is not in your path, in which case you should specify the absolute path to the file.
