### ISSUE TITLE
Test script missing

### ISSUE THREAD

**Issue by XxgithubxX** [brian-lau/MatlabStan#4]
There is no function "runtests" found in the "run_all_tests.m". I'd like to do so and ensure I have a proper install. Where can I find this file?

**Comment by XxgithubxX** [comment]
So I googled that, and it seems like a new matlab function as of 2014. No big deal, I just tried to run the cases independently, but now I'm seeing an error from Matlab:

The specified superclass 'TestCase' contains a parse error or cannot be found on MATLAB's search path, possibly
shadowed by another file with the same name.

**Comment by brian-lau** [comment]
These tests were written for Steve Eddin's xUnit testing framework:

http://www.mathworks.com/matlabcentral/fileexchange/22846-matlab-xunit-test-framework

Unfortunately, Matlab has recently introduced it's own testing framework, that has a runtests function that will get shadowed. If you use Matlab's test framework, one solution is to add the above package to the path, run the MatlabStan tests, and then remove it from the path.

In the next version, I will move to an updated xUnit package that avoids the nameclash.

**Comment by XxgithubxX** [comment]
O...ok...that's what you were referring to in regards to xUnit. I actually read that link and it said there was no need for it since Matlab recently added such a utility, so I just skipped this step assuming it would be ok. I will take your advice for testing purposes. I also wanted to note, not that it's an issue, but if I run the "rats.m" example, I need to put:

pause
print(fit);

If I run the example as is, I get a crash report from "print.exe". Adding the "pause" and waiting until after stan finishes removed this issue. I would note that I'm not using parallel processing, so maybe my computer is too slow causing the race condition. Thanks for the advice though.

**Comment by brian-lau** [comment]
Regarding the example, there is an explicit block method for waiting until sampling finishes, see here:

https://github.com/brian-lau/MatlabStan/wiki/Blocking-the-Matlab-command-line

I will see if adding a catch in the print method can produce a more meaningful message.
