### ISSUE TITLE
Help in setting home directory mac os x 

### ISSUE THREAD

**Issue by MountainHub** [brian-lau/MatlabStan#41]
I obtain the following error:
%%%%%%%%%%
fit = stan('model_code',schools_code,'data',schools_dat);
Error using StanModel/set.stan_home (line 305)
Can't parse stan_home. Is it set correctly?

Error in StanModel (line 185)
         self.stan_home = p.Results.stan_home;

Error in stan (line 108)
   model = StanModel();
%%%%%%%%%%%%%%%

This is probably because of my ignorance. I don't know how to set the directory for cmdstan
My file structure is as follows:
ignorantuser_macpro/CmdStanParent/cmdstan

In stan_home.m I have

d = 'CmdStanParent/';

What should I type in instead?

**Comment by brian-lau** [comment]
You need to indicate the full path of your CmdStan installation. E.g., in `mstan/stan_home.m`

d = '/Users/brian/Documents/Code/cmdstan-2.15.0'

where 'cmdstan-2.15.0' in this case is the root directory of your installation (i.e., there is a 'bin' directory inside 'cmdstan-2.15.0'.

So I'm guessing you need '/Users/ignorantuser_macpro/CmdStanParent/cmdstan'
