### ISSUE TITLE
Stan exits badly

### ISSUE THREAD

**Issue by ashwanijha1** [brian-lau/MatlabStan#42]
Dear Brian/team,

I'm a novice Stan user, using Matlab Stan 2.15 1.0 with Matlab 2015b on Windows 10 64bit. I can get the 'rats' and 'schools' model to work fine, but having an issue getting a survival model to work (adapted from an example at https://www.bioconductor.org/help/course-materials/2016/BioC2016/ConcurrentWorkshops4/Buros/weibull-survival-model.html).

The error is:
Warning: Stan seems to have exited badly. 
> In StanFit/process_exit_failure (line 290)
  In StanFit/process_exit (line 170)
  In StanFit>@(src,evnt)process_exit(self,src,evnt)
  In processState/set.exitValue (line 30)
  In processManager.pollTimerStop (line 508)
  In timer/timercb (line 30)
  In timercb (line 13) 

As far as I can see, output files have all been set-up but all are empty. I'm not sure how to de-bug this?

Many thanks for you help,
Ash

Not sure if it will help but here is some output:

fit.processes.exitValue=70

fit.processes.command=E:\Code\Matlab_Code\Neuro_onc\Stan\anon_model.exe sample num_samples=1000 num_warmup=1000 save_warmup=0 thin=1 adapt engaged=1 gamma=0.05 delta=0.8 kappa=0.75 t0=10 init_buffer=75 term_buffer=50 window=25 algorithm=hmc engine=nuts max_depth=10 metric=diag_e stepsize=1 stepsize_jitter=0 id=1 data file=E:\Code\Matlab_Code\Neuro_onc\Stan\temp.data.R init=2 random seed=210873 output file=output-1.csv diagnostic_file= refresh=100

**Comment by brian-lau** [comment]
Can you share a minimal model and data set that can reproduce this error?

**Comment by ashwanijha1** [comment]
Dear Brian,

Sorry - the problem was at my end.   I mixed up two variables so the input data length was not consistent with the expected vector input length. It works great now!

Thanks for your response and this great software.
