### ISSUE TITLE
Rdump code

### ISSUE THREAD

**Issue by SchollJ** [brian-lau/MatlabStan#43]
Sorry if this is obvious, but I'm not very familiar yet with github. When I look at the 'rdump' file in the github repository the code is different than when I download it zipped (from here: https://github.com/brian-lau/MatlabStan/releases/tag/v2.15.1.0 ). In the file on github, it uses 'deal':
elseif isnumeric(data{i})
39	      fprintf(fid,'%s <- structure(c(%s), .Dim=c(',vars{i},num_list);
40	      [sz(:)] = deal(size(data{i}));
(and Matlab 2016 has problems with 'deal')
while the 'elseif isnumeric' does not feature in the .zip file.

**Comment by brian-lau** [comment]
There have been some changes to the master branch. You can see them here (including the changes to rdump):

https://github.com/brian-lau/MatlabStan/compare/v2.15.1.0...master
