### ISSUE TITLE
Why a model converges using the meanfield algorithm but does not using the fullrank?

### ISSUE THREAD

**Issue by cmelog** [brian-lau/MatlabStan#46]
Hi,

I am using MatlabStan to infer parameters of the following model:

data { 
    int<lower=1> N; //number of time intervals
    int<lower=1> J; //number of sections 
    real<lower=0> y[N,J]; //data points for corrosion model
    real<lower=0> t[N]; //time intervals for data points
} 
transformed data {
    real<lower=0> sigma;
            
    sigma = 7.8; //uncertainty in corrosion model
}
parameters {
    real<lower=0> beta[J];      //scale parameters corrosion growths
    real<lower=0> theta_1[J];   //multiplication parameter corrosion growths
    real<lower=0> theta_2;      //exponent parameter corrosion growths
    real<lower=0> delta_x[N,J]; //estimated corrosion growths
} 
transformed parameters {      
    real<lower=0> mu[J];        //to transform parameter from Stan distribution
    real<lower=0> alpha[N,J];   //shape parameter corrosion growths
    real<lower=0> x[N,J];       //corrosion depths

for (j in 1:J){    
    mu[j] <- 1/beta[j];                             //transformation for Stan Gamma Distribution
    alpha[1,j] <- theta_1[j] * pow(t[1],theta_2);   //shape parameter corrosion growths
    x[1,j] <- delta_x[1,j];                         //corrosion depths
 
    for (n in 2:N){ 
                    alpha[n,j] <- theta_1[j] * (pow(t[n],theta_2)-pow(t[n-1],theta_2));
                    x[n,j] <- delta_x[n,j] + x[n-1,j]; 
                   }
                }
}
model {
theta_2 ~ gamma(0.001,0.001); //prior
for (j in 1:J){       
        theta_1[j] ~ gamma(0.001, 0.001); //prior
        beta[j] ~ gamma(0.001, 0.001);  //prior
    
        delta_x[1,j] ~ gamma(alpha[1,j], mu[j]); //corrosion growths
        y[1,j] ~ normal (x[1,j], sigma);    //likelihood

        for (n in 2:N){ 
                        delta_x[n,j] ~ gamma(alpha[n,j], mu[j]);
                        y[n,j] ~ normal(x[n,j], sigma);
                      }
                }
}

The inferences converges when I use the meanfield algorithm:
Stan is performing variational inference ...
nhg_j_mfvi_c.csv: method = variational
nhg_j_mfvi_c.csv:   variational
nhg_j_mfvi_c.csv:     algorithm = meanfield (Default)
nhg_j_mfvi_c.csv:       meanfield
nhg_j_mfvi_c.csv:     iter = 10000 (Default)
nhg_j_mfvi_c.csv:     grad_samples = 1 (Default)
nhg_j_mfvi_c.csv:     elbo_samples = 100 (Default)
nhg_j_mfvi_c.csv:     eta = 1 (Default)
nhg_j_mfvi_c.csv:     adapt
nhg_j_mfvi_c.csv:       engaged = 1 (Default)
nhg_j_mfvi_c.csv:       iter = 50 (Default)
nhg_j_mfvi_c.csv:     tol_rel_obj = 0.01 (Default)
nhg_j_mfvi_c.csv:     eval_elbo = 100 (Default)
nhg_j_mfvi_c.csv:     output_samples = 1000 (Default)
nhg_j_mfvi_c.csv: id = 1
nhg_j_mfvi_c.csv: data
nhg_j_mfvi_c.csv:   file = C:\MatlabStan-2.15.1.0\temp.data.R
nhg_j_mfvi_c.csv: init = 1
nhg_j_mfvi_c.csv: random
nhg_j_mfvi_c.csv:   seed = 213197
nhg_j_mfvi_c.csv: output
nhg_j_mfvi_c.csv:   file = nhg_j_mfvi_c.csv
nhg_j_mfvi_c.csv:   diagnostic_file =  (Default)
nhg_j_mfvi_c.csv:   refresh = 100 (Default)
nhg_j_mfvi_c.csv: ------------------------------------------------------------
nhg_j_mfvi_c.csv: EXPERIMENTAL ALGORITHM:
nhg_j_mfvi_c.csv:   This procedure has not been thoroughly tested and may be unstable
nhg_j_mfvi_c.csv:   or buggy. The interface is subject to change.
nhg_j_mfvi_c.csv: ------------------------------------------------------------
nhg_j_mfvi_c.csv: Gradient evaluation took 0.009 seconds
nhg_j_mfvi_c.csv: 1000 transitions using 10 leapfrog steps per transition would take 90 seconds.
nhg_j_mfvi_c.csv: Adjust your expectations accordingly!
nhg_j_mfvi_c.csv: Begin eta adaptation.
nhg_j_mfvi_c.csv: Iteration:   1 / 250 [  0%]  (Adaptation)
nhg_j_mfvi_c.csv: Iteration:  50 / 250 [ 20%]  (Adaptation)
nhg_j_mfvi_c.csv: Iteration: 100 / 250 [ 40%]  (Adaptation)
nhg_j_mfvi_c.csv: Iteration: 150 / 250 [ 60%]  (Adaptation)
nhg_j_mfvi_c.csv: Iteration: 200 / 250 [ 80%]  (Adaptation)
nhg_j_mfvi_c.csv: Iteration: 250 / 250 [100%]  (Adaptation)
nhg_j_mfvi_c.csv: Success! Found best value [eta = 0.1].
nhg_j_mfvi_c.csv: Begin stochastic gradient ascent.
nhg_j_mfvi_c.csv:   iter       ELBO   delta_ELBO_mean   delta_ELBO_med   notes 
nhg_j_mfvi_c.csv:    100    -1e+004             1.000            1.000
nhg_j_mfvi_c.csv:    200    -1e+004             0.598            1.000
nhg_j_mfvi_c.csv:    300    -4e+003             1.059            1.000
nhg_j_mfvi_c.csv:    400    -5e+003             0.830            1.000
nhg_j_mfvi_c.csv:    500    -7e+003             0.727            0.316
nhg_j_mfvi_c.csv:    600    -4e+003             0.746            0.841
nhg_j_mfvi_c.csv:    700    -4e+003             0.648            0.316
nhg_j_mfvi_c.csv:    800    -4e+003             0.569            0.316
nhg_j_mfvi_c.csv:    900    -3e+003             0.512            0.195
nhg_j_mfvi_c.csv:   1000    -3e+003             0.461            0.195
nhg_j_mfvi_c.csv:   1100    -3e+003             0.364            0.143
nhg_j_mfvi_c.csv:   1200    -3e+003             0.344            0.057
nhg_j_mfvi_c.csv:   1300    -3e+003             0.149            0.057
nhg_j_mfvi_c.csv:   1400    -3e+003             0.135            0.030
nhg_j_mfvi_c.csv:   1500    -3e+003             0.105            0.028
nhg_j_mfvi_c.csv:   1600    -3e+003             0.022            0.016
nhg_j_mfvi_c.csv:   1700    -3e+003             0.019            0.016
nhg_j_mfvi_c.csv:   1800    -3e+003             0.018            0.016
nhg_j_mfvi_c.csv:   1900    -3e+003             0.012            0.007   MEDIAN ELBO CONVERGED
nhg_j_mfvi_c.csv: Drawing a sample of size 1000 from the approximate posterior... 
nhg_j_mfvi_c.csv: COMPLETED.
stan started processing nhg_j_mfvi_c.csv
stan finished processing nhg_j_mfvi_c.csv

But it does not converge using the fullrank:

Stan is performing variational inference ...
nhg_j_frvi_c.csv: method = variational
nhg_j_frvi_c.csv:   variational
nhg_j_frvi_c.csv:     algorithm = fullrank
nhg_j_frvi_c.csv:       fullrank
nhg_j_frvi_c.csv:     iter = 10000 (Default)
nhg_j_frvi_c.csv:     grad_samples = 1 (Default)
nhg_j_frvi_c.csv:     elbo_samples = 100 (Default)
nhg_j_frvi_c.csv:     eta = 1 (Default)
nhg_j_frvi_c.csv:     adapt
nhg_j_frvi_c.csv:       engaged = 1 (Default)
nhg_j_frvi_c.csv:       iter = 50 (Default)
nhg_j_frvi_c.csv:     tol_rel_obj = 0.01 (Default)
nhg_j_frvi_c.csv:     eval_elbo = 100 (Default)
nhg_j_frvi_c.csv:     output_samples = 1000 (Default)
nhg_j_frvi_c.csv: id = 1
nhg_j_frvi_c.csv: data
nhg_j_frvi_c.csv:   file = C:\MatlabStan-2.15.1.0\temp.data.R
nhg_j_frvi_c.csv: init = 0
nhg_j_frvi_c.csv: random
nhg_j_frvi_c.csv:   seed = 208765
nhg_j_frvi_c.csv: output
nhg_j_frvi_c.csv:   file = nhg_j_frvi_c.csv
nhg_j_frvi_c.csv:   diagnostic_file =  (Default)
nhg_j_frvi_c.csv:   refresh = 100 (Default)
nhg_j_frvi_c.csv: ------------------------------------------------------------
nhg_j_frvi_c.csv: EXPERIMENTAL ALGORITHM:
nhg_j_frvi_c.csv:   This procedure has not been thoroughly tested and may be unstable
nhg_j_frvi_c.csv:   or buggy. The interface is subject to change.
nhg_j_frvi_c.csv: ------------------------------------------------------------
nhg_j_frvi_c.csv: Gradient evaluation took 0.01 seconds
nhg_j_frvi_c.csv: 1000 transitions using 10 leapfrog steps per transition would take 100 seconds.
nhg_j_frvi_c.csv: Adjust your expectations accordingly!
nhg_j_frvi_c.csv: Begin eta adaptation.
nhg_j_frvi_c.csv: Iteration:   1 / 250 [  0%]  (Adaptation)
nhg_j_frvi_c.csv: Iteration:  50 / 250 [ 20%]  (Adaptation)
nhg_j_frvi_c.csv: Iteration: 100 / 250 [ 40%]  (Adaptation)
nhg_j_frvi_c.csv: Iteration: 150 / 250 [ 60%]  (Adaptation)
nhg_j_frvi_c.csv: Iteration: 200 / 250 [ 80%]  (Adaptation)
nhg_j_frvi_c.csv: Iteration: 250 / 250 [100%]  (Adaptation)
nhg_j_frvi_c.csv: Success! Found best value [eta = 0.1].
nhg_j_frvi_c.csv: Begin stochastic gradient ascent.
nhg_j_frvi_c.csv:   iter       ELBO   delta_ELBO_mean   delta_ELBO_med   notes 
nhg_j_frvi_c.csv:    100    -2e+016             1.000            1.000
nhg_j_frvi_c.csv:    200    -7e+005   15347098109.650  30694196218.300
nhg_j_frvi_c.csv:    300    -1e+010   10231398740.100            1.000
nhg_j_frvi_c.csv:    400    -3e+009    7673549055.734            2.635
nhg_j_frvi_c.csv:    500    -1e+019    6138839244.787            1.000
nhg_j_frvi_c.csv:    600    -8e+009    5327331060.280            2.635
nhg_j_frvi_c.csv:    700    -4e+008    4566283768.690            2.635
nhg_j_frvi_c.csv:    800    -3e+008    3995498297.651            2.635
nhg_j_frvi_c.csv:    900    -2e+008    3551554042.413            1.000
nhg_j_frvi_c.csv:   1000    -2e+008    3196398638.182            1.000
nhg_j_frvi_c.csv:   1100    -2e+006    3196398646.930            2.635   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   1200    -8e+007     126979025.198            1.000   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   1300    -2e+017     126979025.198            1.000   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   1400    -2e+006    6824645585.104            1.000   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   1500    -3e+005    6824645585.574            5.702   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   1600    -3e+012    6697666571.900            1.000   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   1700    -4e+008    6697667389.690            1.000   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   1800    -1e+008    6697667389.868            2.153   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   1900    -1e+030    6697667389.916            2.153   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   2000    -7e+008  138428288275062816768.000            5.702   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   2100    -6e+005  138428288275062816768.000            5.702   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   2200    -1e+006  138428288275062816768.000            5.702   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   2300    -4e+008  138428288275062816768.000            5.702   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   2400    -8e+004  138428288268365152256.000            5.702   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   2500    -4e+013  138428288268365152256.000            2.153   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   2600    -8e+005  138428288268370575360.000         1197.049   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   2700    -6e+013  138428288268370575360.000            2.153   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   2800    -3e+007  138428288268370804736.000         1197.049   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   2900    -3e+006  138428288268370804736.000         1197.049   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   3000    -4e+007       5670310.277            8.807   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   3100    -5e+010       5670190.672            1.000   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   3200    -2e+011       5670190.697            1.000   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   3300    -9e+009       5670192.523            8.807   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   3400    -6e+007       5669752.134            8.807   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   3500    -3e+008       5669752.111            8.807   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   3600    -6e+015        243923.504            1.000   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   3700    -1e+005    4952164014.952            8.807   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   3800    -2e+005    4951920109.652            1.000   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   3900    -9e+007    4951920108.871            0.999   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   4000    -4e+004    4951920356.556            1.000   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   4100    -7e+007    4951920356.556            1.000   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   4200    -4e+008    4951920356.567            1.000   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   4300    -3e+007    4951920355.957            1.000   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   4400    -1e+014    4951920341.236            1.000   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   4500    -6e+006    4954227150.505            1.000   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   4600    -6e+007    4954227150.493            1.000   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   4700    -3e+007       2307059.029            0.999   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   4800    -8e+007       2307059.060            0.999   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   4900    -2e+009       2307059.056            0.999   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   5000    -1e+007       2306825.270            0.999   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   5100    -2e+013       2306825.270            1.000   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   5200    -3e+007       2364327.745            1.000   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   5300    -3e+005       2364336.287            1.000   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   5400    -5e+007       2364336.287            1.000   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   5500    -1e+005         57579.169            1.000   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   5600    -2e+010         57579.181            1.000   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   5700    -7e+007         57606.564           98.578   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   5800    -1e+013         57606.601           98.578   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   5900    -4e+007         93719.428          139.917   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   6000    -3e+012         93705.536           98.578   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   6100    -1e+008         96406.442          274.685   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   6200    -4e+006         38907.379           98.578   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   6300    -1e+025         38897.621           34.959   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   6400    -2e+006  462832721509558784.000          274.685   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   6500    -4e+005  462832721509558656.000           34.959   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   6600    -3e+008  462832721509558656.000           34.959   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   6700    -1e+007  462832721509558656.000           29.902   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   6800    -2e+008  462832721509558656.000           29.902   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   6900    -1e+010  462832721509522560.000            4.660   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   7000    -2e+008  462832721509522560.000           29.902   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   7100    -3e+009  462832721509519872.000            4.660   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   7200    -9e+005  462832721509520192.000            4.660   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   7300    -2e+008  462832721509520192.000            4.660   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   7400    -4e+007           347.135            4.433   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   7500    -6e+010           346.769            0.999   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   7600    -6e+004         97230.302            4.433   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   7700    -3e+007         97227.411            0.999   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   7800    -3e+008         97227.408            0.999   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   7900    -6e+007         97227.721            4.113   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   8000    -6e+013         97220.010            1.000   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   8100    -1e+005      63999119.456            4.113   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   8200    -3e+005      63998784.580            1.000   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   8300    -2e+008      63998784.580            1.000   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   8400    -9e+008      63998784.210            0.999   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   8500    -7e+004      64000156.003            1.000   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   8600    -1e+016      63903272.471            1.000   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   8700    -3e+007     118157050.418            1.000   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   8800    -1e+018     118157050.426            1.000   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   8900    -8e+006   15081991457.983            1.000   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   9000    -2e+010   15081991457.983            1.000   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   9100    -1e+005   15018104049.825            1.000   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   9200    -5e+006   15018104049.861            1.000   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   9300    -7e+008   15018104049.861            1.000   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   9400    -4e+010   15018104049.886            1.000   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   9500    -6e+011   15018102678.087            1.000   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   9600    -2e+005   15018342644.502            1.000   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   9700    -2e+005   14964088866.498            0.999   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   9800    -5e+004   14964088866.662            0.999   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   9900    -8e+006        254458.793            0.994   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv:   10000    -1e+010        254458.793            0.994   MAY BE DIVERGING... INSPECT ELBO
nhg_j_frvi_c.csv: Informational Message: The maximum number of iterations is reached! The algorithm may not have converged.
nhg_j_frvi_c.csv: This variational approximation is not guaranteed to be meaningful.
nhg_j_frvi_c.csv: Drawing a sample of size 1000 from the approximate posterior... 
nhg_j_frvi_c.csv: COMPLETED.
stan started processing nhg_j_frvi_c.csv
stan finished processing nhg_j_frvi_c.csv

I am not sure if using the converged meanfield results is accurate enough. I tried to run the model using the NUTS algorithm but used 2.5 hours just with 1000 samples, 1 chain. I also tried before running the model in OPENBUGS for more than 12 hours but never got a result. Your feedback is more than welcome.

**Comment by brian-lau** [comment]
This is a question that seems non-specific to MatlabStan. I think you would probably get good feedback on the Stan forums: http://discourse.mc-stan.org/
