### ISSUE TITLE
Test Case Failure

### ISSUE THREAD

**Issue by XxgithubxX** [brian-lau/MatlabStan#5]
I ran the test cases in the provided directory and upon completion, I get the following:

------------------------------------------------------------------------
FAILED in 1412.983 seconds.

===== Test Case Failure =====
Location: C:\Users\BLAH\Documents\Bayesian_Analysis\STAN\MatlabStan\Tests\TestBernoulli.m
Name:     test_bernoulli_constructor

C:\Users\BLAH\Documents\Bayesian_Analysis\STAN\MatlabStan\Tests\TestBernoulli.m at line 53

CPP file not generated

===== Test Case Failure =====
Location: C:\Users\BLAH\Documents\Bayesian_Analysis\STAN\MatlabStan\Tests\TestStanModel.m
Name:     testSet

C:\Users\BLAH\Documents\Bayesian_Analysis\STAN\MatlabStan\StanModel.m at line 329
C:\Users\BLAH\Documents\Bayesian_Analysis\STAN\MatlabStan\StanModel.m at line 273
C:\Users\BLAH\Documents\Bayesian_Analysis\STAN\MatlabStan\Tests\TestStanModel.m at line 96

File does not exist

===== Test Case Failure =====
Location: C:\Users\BLAH\Documents\Bayesian_Analysis\STAN\MatlabStan\Tests\TestStanModel.m
Name:     testContructorArgs

C:\Users\BLAH\Documents\Bayesian_Analysis\STAN\MatlabStan\StanModel.m at line 329
C:\Users\BLAH\Documents\Bayesian_Analysis\STAN\MatlabStan\StanModel.m at line 219
C:\Users\BLAH\Documents\Bayesian_Analysis\STAN\MatlabStan\Tests\TestStanModel.m at line 47

File does not exist

------------------------------------------------------------------------
I'm not sure what to make of this? I've just recently downloaded everything following the wiki: https://github.com/brian-lau/MatlabStan/wiki/Getting-Started  I should have the latest versions of everything. I'm also using Matlab 2013a on a Windows7 32bit with MinGW/msys compiler. I'm brand new to stan and need it for a class. I just want to be sure I actually have a fully functioning program to begin with. Thanks.

**Comment by brian-lau** [comment]
These failures are due to some reorganization of files in Stan 2.6.0, and have been fixed in the develop branch. I will push out a new release this weekend, but if everything else passed, your installation is working fine.

**Comment by XxgithubxX** [comment]
K thanks. Awesome work on the project!
