### ISSUE TITLE
Problem installing cmdstan on Mac

### ISSUE THREAD

**Issue by magiceule19** [brian-lau/MatlabStan#62]
Hi all,

I think this is a known issue but I have not find any solution so far on the web. I ran the below code in MatlabStan:

model = StanModel('verbose',true);
model.compile('stanc');

schools_code = {
   'data {'
   '    int<lower=0> J;         // number of schools '
   '    real y[J];              // estimated treatment effects'
   '    real<lower=0> sigma[J]; // s.e. of effect estimates '
   '}'
   'parameters {'
   '    real mu; '
   '    real<lower=0> tau;'
   '    real eta[J];'
   '}'
   'transformed parameters {'
   '    real theta[J];'
   '    for (j in 1:J)'
   '    theta[j] = mu + tau * eta[j];'
   '}'
   'model {'
   '    eta ~ normal(0, 1);'
   '    y ~ normal(theta, sigma);'
   '}'
};
  
schools_dat = struct('J',8,...
                     'y',[28 8 -3 7 -1 1 18 12],...
                     'sigma',[15 10 16 11 9 11 10 18]);

fit = stan('model_code',schools_code,'data',schools_dat);

**The error :**

compile: make: `bin/stanc' is up to date.
Compile failed with exit value: 2
Error using StanModel/compile
Warning in '/Users/tasos/Desktop/test.stan', line 3, column 4: Declaration of
    arrays by placing brackets after a variable name is deprecated and will
    be removed in Stan 2.32.0. Instead use the array keyword before the type.
    This can be changed automatically using the auto-format flag to stanc
Warning in '/Users/tasos/Desktop/test.stan', line 4, column 4: Declaration of
    arrays by placing brackets after a variable name is deprecated and will
    be removed in Stan 2.32.0. Instead use the array keyword before the type.
    This can be changed automatically using the auto-format flag to stanc
Warning in '/Users/tasos/Desktop/test.stan', line 9, column 4: Declaration of
    arrays by placing brackets after a variable name is deprecated and will
    be removed in Stan 2.32.0. Instead use the array keyword before the type.
    This can be changed automatically using the auto-format flag to stanc
Warning in '/Users/tasos/Desktop/test.stan', line 12, column 4: Declaration
    of arrays by placing brackets after a variable name is deprecated and
    will be removed in Stan 2.32.0. Instead use the array keyword before the
    type. This can be changed automatically using the auto-format flag to
    stanc
error: half args and returns was enabled in PCH file but is currently disabled
error: PCH file was compiled for the target 'arm64-apple-macosx12.0.0' but the current translation unit
is being compiled for target 'x86_64-apple-macosx12.0.0'
2 errors generated.
make: *** [/Users/tasos/Desktop/test] Error 1

Error in StanModel/sampling (line 736)
            self.compile();

Error in stan (line 138)
      fit = model.sampling(p.Unmatched);

Error in eight_schools_example (line 31)
fit = stan('model_code',schools_code,'data',schools_dat);
 

**I am using:**
Mac 12.5.1 - Processor M1 Pro
MatlabStan 2.15.1.0
CmdStan-2.30.1
gcc --version
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: arm64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by magiceule19** [comment]
solved

**Comment by v738301** [comment]
Hi @magiceule19, I am facing the same problem right now, how did you solve it? Thank you!

**Comment by magiceule19** [comment]
> 

hey, you need to install it from somewhere that arm64 is used. For me works through Spyder terminal.
have a look there:https://github.com/stan-dev/cmdstanr/issues/627
Regards
