### ISSUE TITLE
error extracting samples

### ISSUE THREAD

**Issue by mboedigh** [brian-lau/MatlabStan#7]
line 57:   temp{j} = length(self.(s)(i).(fn{i}));

throws "Index exceeds matrix dimensions." in some cases. 
i is an index into self.samples but is used here to index fn, if i > length(fn) this is an error. In any case j seems like it should be the index into self.samples(i).(fn{j});

**Comment by brian-lau** [comment]
This is fixed in the develop branch. As Stan 2.7.0 appears imminent, I'll fold an updated release then.

Thanks for your help.
