### ISSUE TITLE
Robustness to spaces in paths ?

### ISSUE THREAD

**Issue by piermorel** [brian-lau/MatlabStan#8]
Hello,

I'm just trying to have matlabstan working on a Mac, but I have spaces in the folder names of my matlab working directory paths, which seems cause major problems here... Is there a way to make MatlabStan robust to that ?

**Comment by brian-lau** [comment]
Stan binaries are built using make, which does not appear to handle spaces easily. 
https://www.cmcrossroads.com/article/gnu-make-meets-file-names-spaces-them
http://stackoverflow.com/questions/9838384/can-gnu-make-handle-filenames-with-spaces
http://savannah.gnu.org/bugs/?712

This seems complex enough that I'm gonna recommend not using spaces for now.
