### ISSUE TITLE
"Name Stan Model" pop up for simply runs

### ISSUE THREAD

**Issue by dberma15** [brian-lau/MatlabStan#9]
Hi,

I'm just starting working with matlabstan and I tried running the basic school model from the getting started page. The problem is whenever I run:
fit = stan('model_code',schools_code,'data',schools_dat);
I get a save as window that pops up with the title "Name stan model." If I save it I get the following error:

Error using StanModel/compile (line 852)
uname: not found
uname: not found
cygwin warning:
  MS-DOS style path detected: C:/Users/bermads1/Documents/Daniel
  Preferred POSIX equivalent is: /cygdrive/c/Users/bermads1/Documents/Daniel
  CYGWIN environment variable option "nodosfilewarning" turns off this warning.
  Consult the user's guide for more details about POSIX paths:
    http://cygwin.com/cygwin-ug-net/using.html#using-pathnames
make: **\* No rule to make target `C:/Users/bermads1/Documents/Daniel/quantum'.  Stop.
Error in StanModel/sampling (line 715)
            self.compile();

Error in stan (line 137)
   fit = model.sampling(p.Unmatched);

If I don't save it and press cancel, I get this error:

Error using fileparts (line 34)
Input must be a row vector of characters.

Error in StanModel/update_model (line 1026)
                     [~,name] = fileparts(filename);

Error in StanModel/update_model (line 1003)
                  self.update_model('write',arg);

Error in StanModel/set.model_code (line 416)
            self.update_model('model_code',model);

Error in StanModel/set (line 269)
            self.model_code = p.Results.model_code;

Error in StanModel/sampling (line 709)
         self.set(varargin{:});

Error in stan (line 137)
   fit = model.sampling(p.Unmatched);

I'm really not sure what's going on and how to fix it.

**Comment by brian-lau** [comment]
Looks like you're using Windows. Can you tell me more about your environment? Windows version, Stan version? Can you build an example from the command line?

**Comment by dberma15** [comment]
I'm using windows 7. I just built it yesterday so I'm using matlabstan 2.6.0.0 and cmdstan 2.6.2.

I don't believe I am. I changed the file bernoulli.stan to bernoulli.exe in the directory .\examples\bernoulli and ran 
bernoulli.exe sample data file=bernoulli.data.R
but I got the response 
"Access is denied"

**Comment by brian-lau** [comment]
Sorry, I don't quite understand what you did. Just to be clear, you have compiled the CmdStan components by running (pg 7 CmdStan guide)

```
make build -j2
```

which printed loads of stuff to the command line and should have resulted in some binaries (). Finally, were you able to compile the example by running (pg 9 CmdStan Guide)

```
 make stan/example-models/basic_estimators/bernoulli
````

which should also have printed stuff to the command line and resulted in a C++ file and an .exe file.

**Comment by dberma15** [comment]
I did the make build -j2 and I got what the instructions said I would get. 

For the second line of code, I get the response: 
uname: not found
uname: not found
make: *** No rule to make target 'stan/example-models/basic_estimators/bernoulli'. Stop.

I noticed that there isn't a folder example-models in the folder stan.

**Comment by dberma15** [comment]
I deleted the cmdstan-2.6.2 folder and went through the process again. I noticed at the beginning it says 
uname: not found
uname: not found
However, it ends with 
---CmdStan built---

I've tried copying some of the samples into matlab I get: 
Error using StanModel/compile (line 852)
uname: not found
uname: not found
make: *** No rule to make target `C:/Users/daniel/Documents/Quantum'.  Stop.


Error in StanModel/sampling (line 715)
            self.compile();

Error in stan (line 137)
   fit = model.sampling(p.Unmatched);

**Comment by brian-lau** [comment]
Before getting to Matlab, let's make sure your CmdStan installation works. It seems that you cannot compile the bernoulli example. The examples have moved here:

https://github.com/stan-dev/example-models

Have a look under basic_estimators, and try to compile the bernoulli example as per the manual. Please cut and past the results into your response.

**Comment by dberma15** [comment]
I got the response found on page 10 and 11 of the cmdstan-guide-2.6.2 pdf

**Comment by bdyetton** [comment]
FYI I had this problem too. It was because the path of the matlab file had spaces in it. e.g.
c:/Some Folder/MatlabStanExample.m gives the above

**Comment by brian-lau** [comment]
I'm going to close this as due to a space in path issue. If this is not the case, please reopen.

Stan binaries are built using make, which does not appear to handle spaces easily.
https://www.cmcrossroads.com/article/gnu-make-meets-file-names-spaces-them
http://stackoverflow.com/questions/9838384/can-gnu-make-handle-filenames-with-spaces
http://savannah.gnu.org/bugs/?712

This seems complex enough that I'm gonna recommend not using spaces for now.
